export const SEDES_NURTURE_CAMPAIGN_STEPS = [
  {
    key: 'boas-vindas',
    channel: 'email',
    title: 'Boas-vindas SEDES-DF',
    timing: 'Após cadastro e opt-in',
    summary: 'Explica cadastro, login, acesso gratuito provisório e primeiro diagnóstico.',
    cta: 'Começar na Central',
    path: '/minha-conta/onboarding',
  },
  {
    key: 'diagnostico-pendente',
    channel: 'email',
    title: 'Diagnóstico pendente',
    timing: '24h sem diagnóstico',
    summary: 'Leva o aluno ao diagnóstico para gerar plano, questões e revisão dirigida.',
    cta: 'Iniciar diagnóstico',
    path: '/minha-conta/diagnostico',
  },
  {
    key: 'simulado-semanal',
    channel: 'email',
    title: 'Simulado semanal',
    timing: 'Rotina semanal',
    summary: 'Convida para simulado e boletim de revisão por bloco.',
    cta: 'Abrir simulados',
    path: '/minha-conta/simulados',
  },
  {
    key: 'biblioteca-premium',
    channel: 'interno',
    title: 'Biblioteca premium',
    timing: 'Após liberação de acesso',
    summary: 'Mostra apostila, mapas, resumos, discursiva, questões, simulados e flashcards.',
    cta: 'Ver biblioteca',
    path: '/minha-conta/biblioteca',
  },
  {
    key: 'reativacao-7-dias',
    channel: 'whatsapp',
    title: 'Reativação com opt-in',
    timing: '7 dias sem atividade',
    summary: 'Mensagem curta apontando para caderno de erros e revisão inteligente.',
    cta: 'Revisar agora',
    path: '/minha-conta/progresso',
  },
];
