export const SEDES_LEARNING_ASSETS = [
  {
    id: 'mapa-agente-social-rede',
    specialty: 'Agente Social',
    type: 'Mapa de revisão',
    title: 'Rede socioassistencial e território',
    description: 'Fluxo CRAS, CREAS, referência/contrarreferência, registro e continuidade do acompanhamento.',
    route: '/minha-conta/questoes',
    status: 'ativo',
  },
  {
    id: 'resumo-agente-social-abordagem',
    specialty: 'Agente Social',
    type: 'Resumo específico',
    title: 'Abordagem social sem postura higienista',
    description: 'Autonomia, vínculo, dignidade, recusa de encaminhamento e articulação com a rede.',
    route: '/minha-conta/tutor/redacao',
    status: 'ativo',
  },
  {
    id: 'mapa-agente-social-saude-mental',
    specialty: 'Agente Social',
    type: 'Mapa de revisão',
    title: 'Saúde mental, álcool e outras drogas',
    description: 'Papel socioassistencial, redução de danos, rede de saúde e limites da atuação não clínica.',
    route: '/minha-conta/flashcards',
    status: 'ativo',
  },
  {
    id: 'trilha-servico-social',
    specialty: 'Serviço Social',
    type: 'Trilha por especialidade',
    title: 'Serviço Social — revisão orientada',
    description: 'Organização para receber próximos lotes de questões, simulados e temas específicos.',
    route: '/minha-conta/plano',
    status: 'em preparação',
  },
  {
    id: 'trilha-tecnico-administrativo',
    specialty: 'Técnico Administrativo',
    type: 'Trilha por especialidade',
    title: 'Técnico Administrativo — revisão orientada',
    description: 'Organização para conteúdo administrativo, legislação, documentos e rotina pública.',
    route: '/minha-conta/plano',
    status: 'em preparação',
  },
];
