export const SEDES_LEARNING_ASSETS = [
  {
    id: 'mapa-agente-social-rede',
    specialty: 'Agente Social',
    type: 'Mapa de revisão',
    title: 'Rede socioassistencial e território',
    description: 'Fluxo CRAS, CREAS, referência/contrarreferência, registro e continuidade do acompanhamento.',
    route: '/minha-conta/questoes',
    status: 'ativo',
  },
  {
    id: 'resumo-agente-social-abordagem',
    specialty: 'Agente Social',
    type: 'Resumo específico',
    title: 'Abordagem social sem postura higienista',
    description: 'Autonomia, vínculo, dignidade, recusa de encaminhamento e articulação com a rede.',
    route: '/minha-conta/tutor/redacao',
    status: 'ativo',
  },
  {
    id: 'mapa-agente-social-saude-mental',
    specialty: 'Agente Social',
    type: 'Mapa de revisão',
    title: 'Saúde mental, álcool e outras drogas',
    description: 'Papel socioassistencial, redução de danos, rede de saúde e limites da atuação não clínica.',
    route: '/minha-conta/flashcards',
    status: 'ativo',
  },
  {
    id: 'trilha-servico-social',
    specialty: 'Serviço Social',
    type: 'Trilha por especialidade',
    title: 'Serviço Social — revisão orientada',
    description: 'Organização para receber próximos lotes de questões, simulados e temas específicos.',
    route: '/minha-conta/plano',
    status: 'em preparação',
  },
  {
    id: 'trilha-tecnico-administrativo',
    specialty: 'Técnico Administrativo',
    type: 'Trilha por especialidade',
    title: 'Técnico Administrativo — revisão orientada',
    description: 'Organização para conteúdo administrativo, legislação, documentos e rotina pública.',
    route: '/minha-conta/plano',
    status: 'em preparação',
  },
  {
    id: 'resumo-servico-social-pse',
    specialty: 'Serviço Social',
    type: 'Resumo específico',
    title: 'Proteção Social Especial em situações de violação',
    description: 'Critérios de encaminhamento, sigilo, registro técnico e articulação intersetorial.',
    route: '/minha-conta/questoes',
    status: 'ativo',
  },
  {
    id: 'mapa-tecnico-administrativo-processo',
    specialty: 'Técnico Administrativo',
    type: 'Mapa de revisão',
    title: 'Atos, documentos e rotina administrativa',
    description: 'Fluxo de expediente, registros, formalização e cautelas em atendimento ao cidadão.',
    route: '/minha-conta/flashcards',
    status: 'ativo',
  },
  {
    id: 'resumo-direito-administrativo-autotutela',
    specialty: 'Direito e Legislação',
    type: 'Resumo específico',
    title: 'Autotutela administrativa e segurança jurídica',
    description: 'Anulação, revogação, contraditório, confiança legítima e limites da Administração.',
    route: '/minha-conta/questoes',
    status: 'ativo',
  },
  {
    id: 'mapa-nutricao-sisan-dhaa',
    specialty: 'Nutrição',
    type: 'Mapa de revisão',
    title: 'SISAN, DHAA e políticas públicas de alimentação',
    description: 'Conexões entre direito humano à alimentação adequada, intersetorialidade e controle social.',
    route: '/minha-conta/plano',
    status: 'em preparação',
  },
  {
    id: 'resumo-psicologia-rede-protecao',
    specialty: 'Psicologia',
    type: 'Resumo específico',
    title: 'Escuta, proteção e rede intersetorial',
    description: 'Limites da atuação, acolhimento, encaminhamento responsável e registro técnico.',
    route: '/minha-conta/tutor/redacao',
    status: 'em preparação',
  },
];
