with subject_seed(specialty_slug,slug,title,description,sort_order) as (values
  ('sociologia-411','1-teoria-sociologica-e-conceitos-fundamentais','Teoria Sociológica e Conceitos Fundamentais','1.1 O surgimento da Sociologia e os clássicos: Karl Marx, Émile Durkheim e Max Weber. 1.2 Teoria sociológica contemporânea: Pierre Bourdieu (habitus, campo e capital) e Zygmunt Bauman (modernidade líquida). 1.3 Poder, biopolítica e sexualidade: Michel Foucault (instituições disciplinares, microfísica do poder e a história da sexualidade) e Judith Butler (teoria queer, gênero e performatividade). 1.4 Conceitos estruturantes: Estado, ideologia, socialização e controle social.',10),
  ('sociologia-411','2-pensamento-social-colonialismo-e-relacoes-etnico-raciais','Pensamento Social, Colonialismo e Relações Étnico-Raciais','2.1 Formação histórica e cultural brasileira: raízes da questão social, urbanização e estratificação de classes. 2.2 Colonialismo e perspectivas decoloniais: o pensamento de Frantz Fanon (colonialismo, racismo e a sociologia da descolonização) e as epistemologias do Sul. 2.3 Relações étnico-raciais e interseccionalidade: o mito da democracia racial, o racismo estrutural e a articulação entre raça, classe, gênero e sexualidade na produção das desigualdades sociais.',20),
  ('sociologia-411','3-sociologia-urbana-desigualdades-e-movimentos-sociais','Sociologia Urbana, Desigualdades e Movimentos Sociais','3.1 Sociologia urbana: direito à cidade, segregação socioespacial, gentrificação e periferias. 3.2 O fenômeno da violência urbana e a criminalização da pobreza. 3.3 Ação coletiva e movimentos sociais contemporâneos (urbanos, rurais, movimento negro, feminista e LGBTQIAPN+). 3.4 Sociedade civil, organizações da sociedade civil e participação cidadã no controle social.',30),
  ('sociologia-411','4-metodologia-de-pesquisa-social-e-avaliacao-de-politicas','Metodologia de Pesquisa Social e Avaliação de Políticas','4.1 O debate epistemológico nas Ciências Sociais; métodos quantitativos e qualitativos de pesquisa. 4.2 Técnicas de coleta de dados aplicadas ao estudo de contextos de vulnerabilidade: entrevistas, histórias de vida e etnografia. 4.3 Construção, análise e interpretação de indicadores sociais, raciais e demográficos aplicados ao mapeamento de territórios. 4.4 O papel do sociólogo no monitoramento e na avaliação qualitativa de políticas públicas, inclusive programas governamentais de transferência de renda.',40)
) insert into public.syllabus_nodes(product_id,parent_id,node_type,slug,title,description,sort_order)
select p.id, specialty.id, 'subject', seed.slug, seed.title, seed.description, seed.sort_order
from subject_seed seed
join public.products p on p.slug='nexo-social-sedes-df-2026' and p.active=true
join public.syllabus_nodes specialty on specialty.product_id=p.id
  and specialty.slug=seed.specialty_slug and specialty.node_type='specialty'
on conflict do nothing;

