with subject_seed(specialty_slug,slug,title,description,sort_order) as (values
  ('nutricao-407','4-educacao-alimentar-e-nutricional-ean-e-programas-institucionais','Educação Alimentar e Nutricional (EAN) e Programas Institucionais','4.1 Educação Alimentar e Nutricional (EAN): princípios, metodologias, estratégias educativas e promoção da autonomia dos sujeitos. 4.2 Promoção da alimentação saudável nas comunidades e escolas, incluindo testes de aceitabilidade. 4.3 Programa Nacional de Alimentação Escolar (PNAE) e Conselhos de Alimentação Escolar (CAE).',40),
  ('nutricao-407','5-fundamentos-de-nutricao-e-dietoterapia-basica','Fundamentos de Nutrição e Dietoterapia Básica','5.1 Nutrição básica: carboidratos, proteínas, lipídios, vitaminas e sais minerais. 5.2 Digestão, absorção, metabolismo e recomendações nutricionais. 5.3 Dietoterapia básica voltada às Doenças Crônicas Não Transmissíveis (DCNTs) prevalentes na saúde pública: diabetes mellitus, hipertensão, doenças cardiovasculares e obesidade.',50),
  ('pedagogia-408','1-fundamentos-da-educacao-e-pedagogia-social','Fundamentos da Educação e Pedagogia Social','1.1 Concepções de educação: abordagens críticas, histórico-dialéticas e emancipatórias; educação popular. 1.2 Educação formal, não formal e informal. 1.3 Educação social e pedagogia social: a educação como instrumento de inclusão e garantia de direitos. 1.4 Formação do pedagogo no Brasil e sua atuação em contextos não escolares. 1.5 Desafios contemporâneos da educação em contextos de vulnerabilidade: evasão escolar, analfabetismo, Educação de Jovens e Adultos (EJA), educação inclusiva e diversidade.',10),
  ('pedagogia-408','2-direito-educacional','Direito Educacional','2.1 A Educação na Constituição Federal de 1988. 2.2 Lei de Diretrizes e Bases da Educação Nacional (LDB – Lei Federal nº 9.394/1996 e suas alterações). 2.3 Princípios e organização da educação brasileira; gestão democrática da educação.',20),
  ('pedagogia-408','3-o-pedagogo-no-suas','O Pedagogo no SUAS','Planejamento e Prática Socioeducativa: 3.1 Atribuições e a dimensão pedagógica do trabalho nas equipes do SUAS (CRAS, CREAS e Unidades de Acolhimento). 3.2 Planejamento participativo: elaboração, execução, registro, monitoramento e avaliação de projetos socioeducativos. 3.3 Metodologias participativas e educação em grupo: oficinas, atividades socioeducativas e práticas coletivas. 3.4 Educação, comunidade e território: trabalho socioeducativo voltado ao fortalecimento de vínculos familiares e comunitários. 3.5 Interdisciplinaridade, multidisciplinaridade, trabalho em rede e articulação intersetorial (assistência social, educação, saúde e justiça).',30),
  ('pedagogia-408','4-intervencao-pedagogica-nas-situacoes-de-vulnerabilidade-e-violencia','Intervenção Pedagógica nas Situações de Vulnerabilidade e Violência','4.1 Atuação pedagógica na prevenção e enfrentamento das violências (doméstica, contra a mulher, crianças, adolescentes e idosos). 4.2 Processos educativos com famílias e indivíduos em situações de negligência, abandono, institucionalização e exclusão social. 4.3 A atuação pedagógica em contextos de atendimento a adolescentes em conflito com a lei. 4.4 A intervenção pedagógica na política sobre drogas e nas estratégias de redução de danos. 4.5 Educação para a cidadania, autonomia e protagonismo social. 4.6 Educação em Direitos Humanos: Diretrizes Nacionais para a Educação em Direitos Humanos (Resolução CNE/CP nº 1/2012).',40),
  ('psicologia-409','1-fundamentos-da-psicologia-e-psicologia-social','Fundamentos da Psicologia e Psicologia Social','1.1 História da Psicologia, constituição como ciência e principais abordagens teóricas (psicanálise, cognitivo-comportamental, humanista-existencial e sócio-histórica). 1.2 Psicologia social crítica, o compromisso social da profissão e a interface com as políticas públicas. 1.3 Subjetividade, cultura, diversidade e contexto social. 1.4 Psicologia do Desenvolvimento (infância, adolescência, vida adulta e envelhecimento) e noções de Psicopatologia aplicadas ao contexto da vulnerabilidade social.',10),
  ('psicologia-409','2-a-pratica-psicossocial-no-suas','A Prática Psicossocial no SUAS','2.1 Atribuições, fundamentos ético-metodológicos e a dimensão socioeducativa do psicólogo nas equipes de referência (CRAS, CREAS, Centros Pop e Unidades de Acolhimento). 2.2 Matricialidade sociofamiliar e o trabalho com famílias (transformações e configurações contemporâneas). 2.3 A intervenção psicossocial e a escuta qualificada em situações de violação de direitos, negligência, abandono, institucionalização e medidas socioeducativas. 2.4 Atuação psicossocial na política sobre drogas, populações em situação de rua e estratégias de redução de danos. 2.5 Interdisciplinaridade, trabalho em equipe, articulação intersetorial e atuação em rede.',20),
  ('psicologia-409','3-avaliacao-e-instrumentos-tecnico-operativos','Avaliação e Instrumentos Técnico-Operativos','3.1 Fundamentos da avaliação psicológica e métodos de investigação aplicados ao campo social. 3.2 Instrumentos e técnicas: entrevista psicossocial, anamnese, escuta qualificada, observação e visita domiciliar. 3.3 Metodologias participativas, dinâmica de grupo e o trabalho psicossocial com comunidades. 3.4 Planejamento, monitoramento e avaliação de ações, programas e projetos socioassistenciais.',30),
  ('psicologia-409','4-etica-profissional-e-elaboracao-de-documentos','Ética Profissional e Elaboração de Documentos','4.1 O Código de Ética Profissional do Psicólogo e os princípios fundamentais da atuação. 4.2 Sigilo profissional, responsabilidade técnica e a ética em contextos institucionais e de equipes multiprofissionais. 4.3 Produção de documentos psicológicos (relatórios, laudos, pareceres e registros técnicos) em conformidade com as normativas e resoluções vigentes do Conselho Federal de Psicologia (CFP).',40),
  ('servico-social-410','1-fundamentos-historicos-e-teorico-metodologicos','Fundamentos Históricos e Teórico-Metodológicos','1.1 O processo sócio-histórico de constituição e institucionalização do Serviço Social no Brasil e no mundo; o significado social da profissão. 1.2 As perspectivas e interpretações teórico-metodológicas: conservadorismo, reconceituação e a perspectiva crítico-dialética (influência do materialismo histórico-dialético). 1.3 A questão social e suas expressões na contemporaneidade: transformações societárias, neoliberalismo, reestruturação produtiva e impactos nas demandas e no trabalho profissional.',10),
  ('servico-social-410','2-etica-e-legislacao-profissional','Ética e Legislação Profissional','2.1 Fundamentos ontológicos da ética e da moral; a construção histórica da ética no Serviço Social. 2.2 O projeto ético-político do Serviço Social. 2.3 Lei de Regulamentação da Profissão (Lei Federal nº 8.662/1993 e suas alterações) e Código de Ética Profissional do Assistente Social: princípios, direitos, deveres e competências. 2.4 O sigilo profissional e as normativas do CFESS aplicadas ao exercício profissional. 2.5 Ética em pesquisa envolvendo seres humanos.',20),
  ('servico-social-410','3-dimensao-tecnico-operativa-e-pesquisa-social','Dimensão Técnico-Operativa e Pesquisa Social','3.1 A relação entre teoria, método e prática: a práxis profissional. 3.2 Instrumentos e técnicas de intervenção do Serviço Social: acolhimento, entrevista, visita domiciliar, observação e estudo social. 3.3 Trabalho social com famílias, redes de apoio, grupos e metodologias participativas. 3.4 Elaboração de documentos técnicos: registros, relatórios sociais, laudos sociais e pareceres sociais. 3.5 Interdisciplinaridade e multidisciplinaridade no trabalho social e nas equipes de referência. 3.6 Pesquisa Social: métodos e técnicas qualitativas e quantitativas; a perspectiva crítico-dialética na investigação e elaboração de projetos de pesquisa/intervenção.',30),
  ('servico-social-410','4-estado-politicas-sociais-planejamento-e-gestao','Estado, Políticas Sociais, Planejamento e Gestão','4.1 Estado, políticas sociais e cidadania; as políticas sociais no capitalismo e seus paradigmas teóricos (marxismo, liberalismo, social-democracia). O Estado de Bem-Estar Social (Welfare State) e sua crise. 4.2 A Seguridade Social na Constituição de 1988 (Saúde, Previdência e Assistência Social) e o financiamento das políticas sociais. 4.3 Gestão, Planejamento e Avaliação: teoria das organizações e administração pública; elaboração, planejamento estratégico, monitoramento e avaliação de planos, programas e projetos sociais. 4.4 Orçamento público aplicado às políticas sociais: Plano Plurianual (PPA), Lei de Diretrizes Orçamentárias (LDO) e Lei Orçamentária Anual (LOA). 4.5 Controle social, conselhos gestores, movimentos sociais e participação popular.',40)
) insert into public.syllabus_nodes(product_id,parent_id,node_type,slug,title,description,sort_order)
select p.id, specialty.id, 'subject', seed.slug, seed.title, seed.description, seed.sort_order
from subject_seed seed
join public.products p on p.slug='nexo-social-sedes-df-2026' and p.active=true
join public.syllabus_nodes specialty on specialty.product_id=p.id
  and specialty.slug=seed.specialty_slug and specialty.node_type='specialty'
on conflict do nothing;

