with subject_seed(specialty_slug,slug,title,description,sort_order) as (values
  ('agente-social-200','1-rede-socioassistencial-e-trabalho-no-territorio','Rede Socioassistencial e Trabalho no Território','1.1 Organização e funcionamento dos CRAS, CREAS e Unidades de Acolhimento. 1.2 Territorialização e diagnóstico socioterritorial. 1.3 Articulação com a rede intersetorial: saúde, educação, justiça e segurança pública. 1.4 Fluxos de encaminhamento, referência e contrarreferência no SUAS.',10),
  ('agente-social-200','2-protecao-social-basica-e-trabalho-com-familias-e-comunidades','Proteção Social Básica e Trabalho com Famílias e Comunidades','2.1 Serviço de Proteção e Atendimento Integral à Família (PAIF). 2.2 Serviço de Convivência e Fortalecimento de Vínculos (SCFV). 2.3 Ações de prevenção de situações de vulnerabilidade e risco social. 2.4 Mobilização comunitária e fortalecimento de vínculos familiares e comunitários.',20),
  ('agente-social-200','3-protecao-social-especial-media-e-alta-complexidade','Proteção Social Especial (Média e Alta Complexidade)','3.1 Situações de risco pessoal e social e violação de direitos. 3.2 Papel do CREAS e acompanhamento especializado. 3.3 Noções sobre serviços de acolhimento institucional e familiar. 3.4 Articulação entre serviços e continuidade do atendimento.',30),
  ('agente-social-200','4-abordagem-social-e-populacao-em-situacao-de-rua','Abordagem Social e População em Situação de Rua','4.1 Decreto nº 7.053/2009 (Política Nacional para a População em Situação de Rua). 4.2 Abordagem social no território: princípios, estratégias e postura profissional. 4.3 Construção de vínculo e respeito à autonomia dos usuários. 4.4 Atuação em serviços como Centros POP, abrigos e unidades de acolhimento.',40),
  ('agente-social-200','5-nocoes-de-saude-mental-e-uso-de-alcool-e-outras-drogas','Noções de Saúde Mental e Uso de Álcool e Outras Drogas','5.1 Sofrimento psíquico e vulnerabilidade social. 5.2 Abordagem humanizada e não estigmatizante. 5.3 Noções de redução de danos. 10.4 Articulação com a rede de saúde e atenção psicossocial.',50),
  ('cuidador-social-201','2-rede-socioassistencial-e-intersetorialidade','Rede Socioassistencial e Intersetorialidade','2.1 Articulação entre CRAS, CREAS e Unidades de Acolhimento. 2.2 Trabalho em rede com políticas públicas setoriais, especialmente saúde, educação, justiça e segurança pública. 2.3 Fluxos de encaminhamento, referência e contrarreferência no SUAS. 2.4 Territorialização e matricialidade sociofamiliar.',20),
  ('cuidador-social-201','3-rotinas-de-acolhimento-cuidado-e-trabalho-em-equipe','Rotinas de Acolhimento, Cuidado e Trabalho em Equipe','3.1 Resolução Conjunta CNAS/CONANDA nº 1/2009 (Orientações Técnicas para os Serviços de Acolhimento para Crianças e Adolescentes). 3.2 Plano Nacional de Convivência Familiar e Comunitária. 3.3 Trabalho em equipe interdisciplinar: empatia, comportamento receptivo, comunicação, mediação de conflitos e relacionamento interpessoal. 3.4 Atribuições e limites de atuação do cuidador social no âmbito do SUAS. 3.5 Rotinas humanizadas de cuidado: higiene, alimentação, organização do espaço, acompanhamento de rotinas de saúde e promoção da autonomia dos usuários. 3.6 Construção de vínculos profissionais e promoção da convivência familiar e comunitária.',30),
  ('cuidador-social-201','4-protecao-social-especial-de-alta-complexidade','Proteção Social Especial de Alta Complexidade','4.1 Serviços de acolhimento institucional e familiar. 4.2 Princípios do acolhimento: excepcionalidade, provisoriedade e preservação de vínculos familiares e comunitários. 4.3 Organização e funcionamento dos serviços de acolhimento.',40),
  ('cuidador-social-201','5-populacao-em-situacao-de-rua-e-nocoes-de-abordagem-e-acolhimento-social','População em Situação de Rua e Noções de Abordagem e Acolhimento Social','5.1 Decreto nº 7.053/2009 (Política Nacional para a População em Situação de Rua). 5.2 Noções de abordagem social, convivência e acolhimento em abrigos e casas de passagem. 5.3 Noções de atendimento a usuários com uso problemático de álcool e outras drogas, com abordagem humanizada e não estigmatizante.',50),
  ('cuidador-social-201','6-nocoes-de-saude-mental-e-reducao-de-danos','Noções de Saúde Mental e Redução de Danos','6.1 Sofrimento psíquico e vulnerabilidade social. 6.2 Abordagem humanizada em saúde mental. 6.3 Articulação com a rede de saúde e atenção psicossocial.',60),
  ('tecnico-administrativo-202','1-nocoes-de-direito-constitucional','Noções de Direito Constitucional','1.1 Constituição Federal de 1988: princípios fundamentais. 1.2 Direitos e garantias fundamentais: direitos e deveres individuais e coletivos; direitos sociais. 1.3 Organização do Estado e da Administração Pública: disposições gerais e servidores públicos.',10),
  ('tecnico-administrativo-202','2-nocoes-de-direito-administrativo-e-legislacao','Noções de Direito Administrativo e Legislação','2.1 Estado, governo e administração pública: conceitos e elementos. 2.2 Ato administrativo: conceito, requisitos, atributos, classificação e extinção (anulação e revogação). 2.3 Poderes da Administração Pública: hierárquico, disciplinar, regulamentar e de polícia. 2.4 Regime Jurídico dos Servidores do Distrito Federal (Lei Complementar nº 840/2011 e suas alterações): provimento, vacância, direitos e deveres, responsabilidade e processo administrativo disciplinar.',20),
  ('tecnico-administrativo-202','3-atendimento-rotinas-administrativas-e-arquivologia','Atendimento, Rotinas Administrativas e Arquivologia','3.1 Qualidade no atendimento ao público e trabalho em equipe. 3.2 Noções de redação oficial e comunicações administrativas. 3.3 Organização e controle de documentos: noções de arquivologia; protocolo (recebimento, registro, distribuição e tramitação); tipos de arquivos; métodos de arquivamento; preservação de documentos; e noções de digitalização de documentos.',30),
  ('tecnico-administrativo-202','4-nocoes-de-recursos-materiais-patrimonio-e-compras','Noções de Recursos Materiais, Patrimônio e Compras','4.1 Administração de materiais: classificação, gestão de estoques e armazenagem. 4.2 Gestão patrimonial: tombamento, controle, inventário e baixa de bens. 4.3 Noções de compras no setor público (Lei Federal nº 14.133/2021 e suas alterações): etapas do processo e noções básicas de licitação.',40),
  ('administracao-400','1-teoria-geral-e-processos-administrativos','Teoria Geral e Processos Administrativos','1.1 Evolução do pensamento e da Teoria Administrativa; a administração na sociedade contemporânea. 1.2 Funções administrativas: planejamento, organização, direção e controle. 1.3 Planejamento estratégico, tático e operacional: missão, visão, análise SWOT, Administração por Objetivos (APO), Balanced Scorecard e processo decisório. 1.4 Organização e Direção: estruturas organizacionais, tipos de departamentalização, cultura organizacional, liderança, motivação, comunicação, descentralização e delegação.',10),
  ('administracao-400','2-organizacao-sistemas-metodos-os-m-e-qualidade','Organização, Sistemas, Métodos (OS&M) e Qualidade','2.1 Arquitetura organizacional; mapeamento, análise e distribuição de processos e do trabalho. 2.2 Gráficos de organização e controle (organogramas, fluxogramas), manuais e formulários. 2.3 Gestão da qualidade: principais abordagens, ferramentas da qualidade e modelos de excelência da gestão pública.',20),
  ('administracao-400','3-gestao-de-projetos','Gestão de Projetos','3.1 Elaboração, análise, avaliação e etapas dos projetos. 3.2 Principais características dos modelos de gestão de projetos.',30),
  ('administracao-400','4-administracao-financeira-e-orcamentaria-afo','Administração Financeira e Orçamentária (AFO)','4.1 Princípios, diretrizes e processo orçamentário; métodos, técnicas e normas legais aplicáveis. 4.2 Receita pública: categorias, fontes, estágios e dívida ativa. 4.3 Despesa pública: categorias e estágios. 4.4 Suprimento de fundos, Restos a Pagar e Despesas de Exercícios Anteriores. 4.5 Sistemas de planejamento, orçamento e execução financeira no Distrito Federal: SIAFEM-DF e demais instrumentos aplicáveis.',40),
  ('administracao-400','5-gestao-de-pessoas','Gestão de Pessoas','5.1 Conceitos e importância. 5.2 Fundamentos da administração e impactos na gestão de pessoas. 5.3 Funções do órgão de recursos humanos. 5.4 Comportamento organizacional. 5.5 Competência interpessoal e gerenciamento de conflitos. 5.6 Gestão da mudança. 5.7 Recrutamento e seleção. 5.8 Análise e descrição de cargos. 5.9 Gestão de desempenho. 5.10 Desenvolvimento e capacitação de pessoal. 5.11 Administração de cargos, carreiras e salários. 5.12 Gestão por competências. 5.13 Tendências em gestão de pessoas no setor público.',50),
  ('administracao-400','6-etica-e-conduta-profissional','Ética e Conduta Profissional','6.1 Ética no serviço público: comportamento profissional, atitudes no serviço e organização do trabalho.',60)
) insert into public.syllabus_nodes(product_id,parent_id,node_type,slug,title,description,sort_order)
select p.id, specialty.id, 'subject', seed.slug, seed.title, seed.description, seed.sort_order
from subject_seed seed
join public.products p on p.slug='nexo-social-sedes-df-2026' and p.active=true
join public.syllabus_nodes specialty on specialty.product_id=p.id
  and specialty.slug=seed.specialty_slug and specialty.node_type='specialty'
on conflict do nothing;
