with subject_seed(specialty_slug,slug,title,description,sort_order) as (values
  ('ciencias-contabeis-401','1-contabilidade-geral-e-societaria','Contabilidade Geral e Societária','1.1 Estrutura conceitual da contabilidade; ambiente econômico, processo de tomada de decisão e estabelecimento de normas contábeis. 1.2 Conceito de lucro: receitas, despesas, ganhos e perdas. 1.3 Mensuração e avaliação de ativo e passivo; patrimônio líquido. 1.4 Evidenciação contábil.',10),
  ('ciencias-contabeis-401','2-administracao-financeira-e-analise-de-balancos','Administração Financeira e Análise de Balanços','2.1 Conceitos, métodos e análise da liquidez. 2.2 Planejamento e controle de caixa; equilíbrio financeiro e necessidade de capital de giro (integração entre capital de giro, caixa e lucro). 2.3 Análise e controle de estoques e valores a receber. 2.4 O dilema risco x rentabilidade e a gestão do valor no capital de giro.',20),
  ('ciencias-contabeis-401','3-contabilidade-aplicada-ao-setor-publico-casp','Contabilidade Aplicada ao Setor Público (CASP)','3.1 A Contabilidade Pública e seu ambiente. 3.2 Manual de Contabilidade Aplicada ao Setor Público (MCASP). 3.3 Plano de Contas Aplicado ao Setor Público (PCASP). 3.4 Demonstrações Contábeis Aplicadas ao Setor Público (DCASP) e análise de balanços públicos. 3.5 Normas Brasileiras de Contabilidade Aplicadas ao Setor Público (NBC TSP). 3.6 Procedimentos Contábeis Orçamentários e Procedimentos Contábeis Patrimoniais: critérios de mensuração, reconhecimento e evidenciação.',30),
  ('ciencias-contabeis-401','4-orcamento-publico-administracao-financeira-e-orcamentaria-afo','Orçamento Público/Administração Financeira e Orçamentária (AFO)','4.1 Evolução conceitual e princípios orçamentários; natureza jurídica do orçamento; métodos, técnicas e normas legais aplicáveis. 4.2 Lei Federal nº 4.320/1964 e suas alterações; e Lei Complementar nº 101/2000 e suas alterações (Lei de Responsabilidade Fiscal). 4.3 Plano Plurianual (PPA), Lei de Diretrizes Orçamentárias (LDO) e Lei Orçamentária Anual (LOA): organização e trâmite no Legislativo. 4.4 Execução orçamentária: programação dos desembolsos; estágios da receita e da despesa; créditos adicionais; restos a pagar.',40),
  ('ciencias-contabeis-401','5-auditoria-contabil-e-governamental','Auditoria Contábil e Governamental','5.1 Campo de atuação, marco legal, princípios, normas e técnicas de auditoria. 5.2 Controles internos: planejamento, execução e avaliação dos trabalhos. 5.3 Papéis de trabalho, pareceres e relatórios de auditoria. 5.4 Auditoria com enfoque de ciclos: auditoria de receitas, compras, estoques, caixa, ativos e passivos de curto e longo prazo, patrimônio líquido e transações com partes relacionadas.',50),
  ('comunicacao-social-402','1-fundamentos-e-teorias-da-comunicacao','Fundamentos e Teorias da Comunicação','1.1 Processos fundamentais da comunicação e a construção social da realidade. 1.2 Teoria da Comunicação: principais escolas, correntes sociológicas e pensadores. 1.3 Cultura, representações sociais e a natureza social do fenômeno comunicacional. 1.4 O papel do comunicador na sociedade de massas e sua dimensão política.',10),
  ('comunicacao-social-402','2-comunicacao-organizacional-e-relacoes-publicas','Comunicação Organizacional e Relações Públicas','2.1 Planejamento estratégico de comunicação organizacional. 2.2 Mapeamento e relacionamento com os públicos de uma instituição (internos e externos). 2.3 Comunicação dirigida, comunicação interna e comunicação institucional. 2.4 Responsabilidade social, gestão de relacionamento com a comunidade e cidadania. 2.5 Pesquisas de opinião e de públicos (métodos qualitativos, quantitativos, amostragem e grupos focais).',20),
  ('comunicacao-social-402','3-jornalismo-assessoria-de-imprensa-e-gestao-de-crise','Jornalismo, Assessoria de Imprensa e Gestão de Crise','3.1 Técnicas de assessoria de imprensa e relacionamento com a mídia. 3.2 Produção e edição de conteúdo: press-release, press-kit e notas oficiais. 3.3 Organização de entrevistas coletivas e media training. 3.4 Monitoramento de mídia (clipping) e análise de imagem. 3.5 Gestão de comunicação em situação de risco e gerenciamento de crises de imagem no setor público.',30),
  ('comunicacao-social-402','4-comunicacao-digital-e-novas-tecnologias','Comunicação Digital e Novas Tecnologias','4.1 A cibercultura, a digitalização e a sociedade em rede. 4.2 Convergência midiática e as novas mídias digitais. 4.3 Planejamento e gestão de comunicação em mídias sociais (redes sociais institucionais/governamentais). 4.4 Produção de conteúdo para web e métricas de monitoramento digital.',40),
  ('comunicacao-social-402','5-etica-profissional','Ética profissional','5.1 Noções de moral, ética e deontologia. 5.2 Os Códigos de Ética no campo da Comunicação (Jornalismo e Relações Públicas). 5.3 Ética e responsabilidade na comunicação pública.',50),
  ('direito-e-legislacao-403','1-direito-civil','Direito Civil','1.1 Lei de Introdução às Normas do Direito Brasileiro (LINDB). 1.2 Pessoas. 1.2.1 Pessoa natural. 1.2.2 Personalidade e capacidade. 1.2.3 Direitos da personalidade. 1.2.4 Pessoa jurídica. 1.2.5 Domicílio. 1.3 Bens. 1.3.1 Classificação geral dos bens. 1.3.2 Bens móveis e imóveis. 1.3.3 Bens fungíveis e infungíveis. 1.3.4 Bens consumíveis e inconsumíveis. 1.3.5 Bens divisíveis e indivisíveis. 1.3.6 Bens singulares e coletivos. 1.3.7 Bens públicos e privados. 1.3.8 Bens considerados em si mesmos. 1.3.9 Bens reciprocamente considerados. 1.4 Fato jurídico. 1.4.1 Negócio jurídico. 1.4.2 Defeitos do negócio jurídico. 1.4.3 Invalidade do negócio jurídico. 1.4.4 Atos jurídicos lícitos. 1.4.5 Atos ilícitos. 1.5 Prescrição e decadência. 1.6 Prova. 1.7 Obrigações. 1.7.1 Modalidades. 1.7.2 Transmissão das obrigações. 1.7.3 Adimplemento e extinção das obrigações. 1.7.4 Inadimplemento das obrigações. 1.8 Contratos. 1.8.1 Disposições gerais e princípios contratuais: boa‑fé objetiva, função social, equilíbrio contratual. 1.8.2 Formação, interpretação e revisão dos contratos. 1.8.3 Estipulação em favor de terceiro. 1.8.4 Cláusulas gerais contratuais. 1.8.5 Vícios redibitórios. 1.8.6 Evicção. 1.8.7 Extinção dos contratos. 1.8.8 Contratos em espécie (introdução): compra e venda, locação, prestação de serviços, comodato, mútuo, mandato, doação. 1.9 Responsabilidade civil. 1.9.1 Elementos da responsabilidade civil. 1.9.2 Responsabilidade subjetiva e objetiva. 1.9.3 Nexo causal, dano e culpa. 1.9.4 Excludentes de responsabilidade. 1.9.5 Responsabilidade civil do Estado e de terceiros.',10),
  ('direito-e-legislacao-403','2-direito-processual-civil','Direito Processual Civil','2.1 Normas processuais civis. 2.2 Função jurisdicional. 2.3 Ação. 2.4 Pressupostos processuais. 2.5 Preclusão. 2.6 Sujeitos do processo. 2.7 Litisconsórcio. 2.8 Intervenção de terceiros. 2.9 Poderes, deveres e responsabilidade do juiz. 2.10 Ministério Público. 2.11 Advocacia Pública. 2.12 Defensoria Pública. 2.13 Atos processuais. 2.14 Tutela provisória (tutela de urgência e tutela de evidência). 2.15 Formação, suspensão e extinção do processo. 2.16 Procedimento comum: fases postulatória e saneadora (petição inicial, contestação, reconvenção, providências preliminares e saneamento do processo).',20),
  ('direito-e-legislacao-403','3-direito-constitucional','Direito Constitucional','3.1 Constituição: conceito, classificações e aplicabilidade das normas constitucionais. 3.2 Princípios fundamentais da República. 3.3 Direitos e garantias fundamentais: direitos e deveres individuais e coletivos, direitos sociais, nacionalidade e direitos políticos. 3.4 Organização político-administrativa do Estado (União, Estados, Distrito Federal e Municípios). 3.5 Da Administração Pública na Constituição. 3.6 Organização dos Poderes: Legislativo, Executivo e Judiciário. 3.7 Funções essenciais à Justiça. 3.8 Controle de Constitucionalidade.',30),
  ('direito-e-legislacao-403','4-direito-administrativo','Direito Administrativo','4.1 Estado, Governo e Administração Pública: conceitos, elementos e organização. 4.2 Princípios expressos e implícitos da Administração Pública. 4.3 Atos administrativos: conceito, requisitos, atributos, classificações, espécies e invalidação. 4.4 Poderes administrativos. 4.5 Controle da Administração Pública: controle interno, externo, parlamentar, jurisdicional e atuação dos Tribunais de Contas. 4.6 Processo Administrativo: Lei Federal nº 9.784/1999 e sua aplicação no Distrito Federal, nos termos da Lei Distrital nº 2.834/2001. 4.7 Lei de Improbidade Administrativa (Lei Federal nº 8.429/1992 e suas alterações recentes). 4.8 Licitações e Contratos Administrativos: Lei Federal nº 14.133/2021 e suas alterações. 4.9 Terceiro Setor e Marco Regulatório das Organizações da Sociedade Civil – MROSC (Lei Federal nº 13.019/2014 e suas alterações).',40)
) insert into public.syllabus_nodes(product_id,parent_id,node_type,slug,title,description,sort_order)
select p.id, specialty.id, 'subject', seed.slug, seed.title, seed.description, seed.sort_order
from subject_seed seed
join public.products p on p.slug='nexo-social-sedes-df-2026' and p.active=true
join public.syllabus_nodes specialty on specialty.product_id=p.id
  and specialty.slug=seed.specialty_slug and specialty.node_type='specialty'
on conflict do nothing;
