with subject_seed(specialty_slug,slug,title,description,sort_order) as (values
  ('direito-e-legislacao-403','5-direito-financeiro','Direito Financeiro','5.1 Finanças públicas na Constituição Federal. 5.2 Orçamento público: conceitos e princípios. Plano Plurianual (PPA), Lei de Diretrizes Orçamentárias (LDO) e Lei Orçamentária Anual (LOA). 5.3 Normas Gerais de Direito Financeiro (Lei Federal nº 4.320/1964 e suas alterações): receita pública, despesa pública, estágios e créditos adicionais. 5.4 Lei Complementar nº 101/2000 e suas alterações (Lei de Responsabilidade Fiscal).',50),
  ('direito-e-legislacao-403','6-transparencia-e-protecao-de-dados','Transparência e Proteção de Dados','6.1 Lei Geral de Proteção de Dados Pessoais – LGPD (Lei Federal nº 13.709/2018 e suas alterações): fundamentos, princípios, direitos dos titulares e tratamento de dados pessoais pelo Poder Público. 6.2 Lei de Acesso à Informação – LAI (Lei Federal nº 12.527/2011 e suas alterações) e sua regulamentação no âmbito do Distrito Federal (Lei Distrital nº 4.990/2012).',60),
  ('economia-404','1-teoria-economica-microeconomia-e-macroeconomia','Teoria Econômica (Microeconomia e Macroeconomia)','1.1 Conceitos fundamentais: oferta, demanda, elasticidades, mercado e equilíbrio. 1.2 Microeconomia: estruturas de mercado, monopólio, concorrência monopolística, mercado de fatores e Teoria dos Jogos. 1.3 Falhas de mercado: externalidades, bens públicos e informação assimétrica. 1.4 Equilíbrio geral, Economia do Bem-Estar e Teoria da Escolha Pública.',10),
  ('economia-404','2-economia-do-setor-publico','Economia do Setor Público','2.1 O Setor Público em economias de mercado e o Setor Público no Brasil. 2.2 Teoria da despesa pública, orçamento e gastos públicos. 2.3 Teoria da tributação e Federalismo Fiscal.',20),
  ('economia-404','3-economia-social','Economia Social','Pobreza, Desigualdade e Distribuição de Renda: 3.1 Distribuição funcional e pessoal da renda; concentração de renda e métricas de desigualdade. 3.2 Pobreza: conceitos, mensuração, pobreza absoluta e relativa, extrema pobreza e pobreza multidimensional. 3.3 Crescimento econômico, desenvolvimento, exclusão social e políticas públicas de combate à pobreza e redução das desigualdades no Distrito Federal, com ênfase em transferência de renda, assistência social, segurança alimentar e inclusão produtiva, bem como análise de impacto social e econômico de programas e ações governamentais.',30),
  ('educador-social-405','1-fundamentos-da-politica-social-e-dinamica-familiar','Fundamentos da Política Social e Dinâmica Familiar','1.1 A Seguridade Social no Brasil: conceito, organização, financiamento e trajetória histórica. 1.2 Matricialidade sociofamiliar, territorialização e vigilância socioassistencial no âmbito do SUAS. 1.3 A família contemporânea: transformações, novas configurações e dinâmicas de vulnerabilidade social. 1.4 Políticas públicas no Brasil: conceito, formulação, ciclo, implementação e avaliação.',10),
  ('educador-social-405','2-a-pratica-socioeducativa-nos-servicos-do-suas','A Prática Socioeducativa nos Serviços do SUAS','2.1 A inserção e o papel do Educador Social na Proteção Social Básica: Serviço de Proteção e Atendimento Integral à Família (PAIF) e Serviço de Convivência e Fortalecimento de Vínculos (SCFV). 2.2 A inserção e o papel do Educador Social na Proteção Social Especial: Serviço de Proteção e Atendimento Especializado a Famílias e Indivíduos (PAEFI) e Serviço Especializado em Abordagem Social. 2.3 Serviços de acolhimento institucional e familiar: rotinas, mediação de conflitos e construção de autonomia. 2.4 Rede de proteção social: fluxos de atendimento, encaminhamento e intersetorialidade (Assistência Social, Saúde, Educação e Justiça).',20),
  ('educador-social-405','3-metodologia-do-trabalho-social-e-abordagem','Metodologia do Trabalho Social e Abordagem','3.1 Trabalho social com famílias, indivíduos e grupos. 3.2 Abordagem social em contextos de alta vulnerabilidade e risco nas ruas e nos abrigos. 3.3 Acolhimento, escuta qualificada, construção de vínculos e acompanhamento sociofamiliar. 3.4 Interdisciplinaridade, multidisciplinaridade e trabalho em equipe. 3.5 Planejamento, execução, registro, monitoramento e avaliação de ações socioeducativas.',30),
  ('educador-social-405','4-temas-contemporaneos-e-diretrizes-internacionais','Temas Contemporâneos e Diretrizes Internacionais','4.1 Política Nacional sobre Drogas, dependência química e estratégias de Redução de Danos. 4.2 Orientações Técnicas: Serviços de Acolhimento para Crianças e Adolescentes (Resolução Conjunta CNAS/CONANDA nº 1/2009). 4.3 Declaração Universal dos Direitos Humanos e Convenção sobre os Direitos da Criança. 4.4 Diretrizes a RIAD: diretrizes das Nações Unidas para Prevenção da Prática de Infrações por adolescentes. 4.5 Regras Mínimas da ONU para a Administração da Justiça da Infância e da Juventude (Regras de Beijing).',40),
  ('estatistica-406','1-estatistica-descritiva-e-analise-exploratoria-de-dados','Estatística Descritiva e Análise Exploratória de Dados','1.1 Tipos de dados, bancos de dados, ordem de grandeza, precisão e arredondamento. 1.2 Proporções, porcentagens, taxas e números índices (indicadores sociais). 1.3 Representação gráfica e tabular: tabelas de frequências, histogramas, gráficos de barras, gráficos de setores e boxplot. 1.4 Medidas resumo: medidas de posição, dispersão, assimetria e curtose. 1.5 Associação entre variáveis qualitativas e quantitativas: tabelas de contingência, coeficientes de associação, risco relativo e razão de chances (odds ratio). 1.6 Elaboração de relatórios técnicos e apresentações gerenciais.',10),
  ('estatistica-406','2-probabilidade-e-inferencia-estatistica','Probabilidade e Inferência Estatística','2.1 Noções sobre amostragem e distribuições amostrais. Teorema Limite Central. 2.2 Estimação pontual e por intervalo (intervalos de confiança). 2.3 Testes de hipóteses para médias e variâncias; testes qui-quadrado (aderência, homogeneidade e independência). 2.4 Inferência Bayesiana: probabilidade subjetiva, método bayesiano, intervalos de credibilidade e testes de hipóteses. 2.5 Testes não paramétricos.',20),
  ('estatistica-406','3-modelagem-estatistica-e-analise-multivariada','Modelagem Estatística e Análise Multivariada','3.1 Álgebra matricial básica aplicada à estatística. 3.2 Análise de regressão e correlação: regressão linear simples e múltipla, regressão logística e técnicas de suavização. 3.3 Análise de variância (ANOVA com um ou mais fatores). 3.4 Análise multivariada: componentes principais, análise fatorial, análise de agrupamentos (cluster), discriminação e classificação, correspondência e correlação canônica. 3.5 Modelos de equações estruturais. 3.6 Análise de sobrevivência e tábuas atuariais.',30),
  ('estatistica-406','4-gestao-e-exploracao-de-bancos-de-dados','Gestão e Exploração de Bancos de Dados','4.1 Noções de modelagem de bancos de dados: projeto conceitual, lógico e físico. 4.2 Modelo Entidade-Relacionamento e Modelo Relacional. 4.3 Linguagens do modelo relacional (álgebra relacional e cálculo relacional) e Linguagem SQL (comandos de definição e manipulação de dados). 4.4 Introdução a bancos de dados multidimensionais e ferramentas de apoio à análise estatística.',40),
  ('nutricao-407','1-seguranca-alimentar-e-nutricional-san-e-politicas-publicas','Segurança Alimentar e Nutricional (SAN) e Políticas Públicas','1.1 O Direito Humano à Alimentação Adequada (DHAA) e a Soberania Alimentar. 1.2 Sistema Nacional de Segurança Alimentar e Nutricional (SISAN). 1.3 Política Nacional de Alimentação e Nutrição (PNAN). 1.4 Instâncias de controle social em Segurança Alimentar e Nutricional, com ênfase no Conselho Nacional de Segurança Alimentar e Nutricional (CONSEA). 1.5 Gestão de Equipamentos Públicos de Segurança Alimentar e Nutricional (Restaurantes Comunitários, Bancos de Alimentos e Cozinhas Comunitárias).',10),
  ('nutricao-407','2-nutricao-em-saude-publica-e-epidemiologia','Nutrição em Saúde Pública e Epidemiologia','2.1 Epidemiologia nutricional: determinantes sociais da desnutrição, obesidade, anemia e hipovitaminose A em populações vulneráveis. 2.2 Avaliação nutricional de coletividades e indivíduos. 2.3 Nutrição nos ciclos da vida (gestação, pediatria, vida adulta e envelhecimento). 2.4 Aleitamento materno e alimentação complementar.',20),
  ('nutricao-407','3-gestao-de-unidades-de-alimentacao-e-nutricao-uan','Gestão de Unidades de Alimentação e Nutrição (UAN)','3.1 Administração em Serviços de Alimentação: planejamento, organização, coordenação e controle de UANs. 3.2 Higiene de alimentos, manipuladores, ambiente, equipamentos e utensílios. 3.3 Controle sanitário: contaminação e alteração de alimentos; micro-organismos e toxinfecções alimentares. 3.4 Legislação sanitária, Boas Práticas de Fabricação (BPF) e avaliação da qualidade. 3.5 Técnica dietética: conceito, características, pré-preparo e preparo dos alimentos.',30)
) insert into public.syllabus_nodes(product_id,parent_id,node_type,slug,title,description,sort_order)
select p.id, specialty.id, 'subject', seed.slug, seed.title, seed.description, seed.sort_order
from subject_seed seed
join public.products p on p.slug='nexo-social-sedes-df-2026' and p.active=true
join public.syllabus_nodes specialty on specialty.product_id=p.id
  and specialty.slug=seed.specialty_slug and specialty.node_type='specialty'
on conflict do nothing;

