import React,{useEffect,useMemo,useState}from'react';
import{Helmet}from'react-helmet';import{Link}from'react-router-dom';import{ChevronLeft,Layers3,Loader2}from'lucide-react';
import{Button}from'@/components/ui/button.jsx';import{getMyFlashcards,reviewFlashcard}from'@/api/flashcards.js';
const RATINGS=[['again','Rever'],['hard','Difícil'],['good','Bom'],['easy','Fácil']];
const FlashcardsPage=()=>{const[decks,setDecks]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null),[index,setIndex]=useState(0),[flipped,setFlipped]=useState(false),[busy,setBusy]=useState(false);
useEffect(()=>{let m=true;getMyFlashcards().then(({data,error:e})=>{if(m){setDecks(data);setError(e);setLoading(false);}});return()=>{m=false;};},[]);
const due=useMemo(()=>{const now=Date.now();return decks.flatMap(d=>d.flashcards.map(c=>({...c,deckTitle:d.title}))).filter(c=>!c.progress||new Date(c.progress.next_review_at).getTime()<=now);},[decks]);const card=due[index];
const rate=async(rating)=>{setBusy(true);const{error:e}=await reviewFlashcard(card.id,rating);if(e)setError(e);else{setFlipped(false);setIndex(i=>i+1);}setBusy(false);};
return <><Helmet><title>Flashcards - NORTIS CONCURSOS</title></Helmet><div className="min-h-screen bg-background py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8"><Link to="/minha-conta" className="mb-6 inline-flex items-center text-sm font-semibold text-[hsl(var(--accent))] hover:underline"><ChevronLeft className="mr-1 h-4 w-4"/>Central Nortis</Link><p className="text-xs font-bold uppercase tracking-[.16em] text-[hsl(var(--accent))]">Central Nortis</p><h1 className="mt-2 text-3xl font-bold">Flashcards</h1><p className="mt-3 text-muted-foreground">Revise no ritmo calculado a partir da dificuldade de cada cartão.</p>
{loading?<Loader2 className="mx-auto mt-16 h-8 w-8 animate-spin"/>:error?<p className="mt-8 rounded-2xl bg-card p-6 text-muted-foreground">{error}</p>:decks.length===0?<div className="mt-8 rounded-2xl bg-card p-8 text-center"><Layers3 className="mx-auto mb-4 h-10 w-10 text-muted-foreground"/><h2 className="text-xl font-semibold">Flashcards em preparação</h2><p className="mt-2 text-sm text-muted-foreground">Os baralhos serão publicados após validação editorial.</p></div>:!card?<div className="mt-8 rounded-2xl bg-card p-8 text-center"><Layers3 className="mx-auto mb-4 h-10 w-10 text-emerald-600"/><h2 className="text-xl font-semibold">Revisão do dia concluída</h2><p className="mt-2 text-sm text-muted-foreground">Volte quando houver novos cartões programados.</p></div>:<div className="mt-8"><p className="mb-3 text-sm text-muted-foreground">{card.deckTitle} · {index+1} de {due.length}</p><button type="button" onClick={()=>setFlipped(v=>!v)} className="min-h-72 w-full rounded-2xl border border-border bg-card p-8 text-center shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--accent))]"><span className="text-xs font-bold uppercase text-[hsl(var(--accent))]">{flipped?'Resposta':'Pergunta'}</span><span className="mt-6 block text-xl font-semibold">{flipped?card.back_text:card.front_text}</span><span className="mt-8 block text-xs text-muted-foreground">Clique para {flipped?'ver a pergunta':'revelar a resposta'}</span></button>{flipped&&<div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{RATINGS.map(([value,label])=><Button key={value} variant="outline" disabled={busy} onClick={()=>rate(value)}>{label}</Button>)}</div>}</div>}
</div></div></>};export default FlashcardsPage;
